#!/bin/bash

CONF_DIR=/opt/conf/lms-qiniu-transfer
CONF_FILE=${CONF_DIR}/prod.py

mkdir -p ${CONF_DIR}

cat <<EOF > ${CONF_FILE}
HOST = '${HOST}'
PORT = ${PORT}
USER = '${USER}'
PASSWORD = '${PASSWORD}'
DATABASE = '${DATABASE}'
QINIU_STORAGE_BUCKET_NAME = "${QINIU_STORAGE_BUCKET_NAME}"
QINIU_STORAGE_BUCKET_DOMAIN = "${QINIU_STORAGE_BUCKET_DOMAIN}"
QINIU_STORAGE_ACCESS_KEY = "${QINIU_STORAGE_ACCESS_KEY}"
QINIU_STORAGE_SECRET_KEY = "${QINIU_STORAGE_SECRET_KEY}"
EOF


cron -f